"""
Jobs API Routes
Endpoints for job queue management and monitoring.
"""
import sys
import os
from typing import Optional, List
from datetime import datetime

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

# Add the repository and api directories before importing shared API helpers.
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__)))))
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from job_lifecycle import (
    ACTIVE_JOB_STATUSES,
    isoformat_utc,
    reconcile_stale_jobs,
    transition_job,
)

router = APIRouter()


class JobStatus(BaseModel):
    """Job status model"""
    id: str
    status: str
    config: Optional[dict]
    created_at: Optional[str]
    started_at: Optional[str]
    completed_at: Optional[str]
    result: Optional[dict]
    error: Optional[str]


class JobListResponse(BaseModel):
    """Response for job list endpoint"""
    jobs: List[JobStatus]
    total: int


@router.get("", response_model=JobListResponse)
async def list_jobs(
    status: Optional[str] = Query(default=None, description="Filter by status: pending, running, completed, failed"),
    limit: int = Query(default=20, ge=1, le=100),
    offset: int = Query(default=0, ge=0)
):
    """
    List all jobs with optional filtering.
    """
    try:
        from supabase_storage import get_supabase_client
        supabase = get_supabase_client()

        # Check if supabase is None
        if supabase is None:
            return JobListResponse(jobs=[], total=0)

        reconcile_stale_jobs(supabase)

        # Get total count
        count_query = supabase.table("job_queue").select("id", count="exact")
        if status:
            count_query = count_query.eq("status", status)
        count_result = count_query.execute()
        total = count_result.count if count_result.count else 0

        # Get jobs
        query = supabase.table("job_queue").select("*").order("created_at", desc=True)

        if status:
            query = query.eq("status", status)

        query = query.range(offset, offset + limit - 1)

        result = query.execute()

        return JobListResponse(
            jobs=result.data if result.data else [],
            total=total
        )

    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to list jobs: {str(e)}")


@router.get("/{job_id}", response_model=JobStatus)
async def get_job(job_id: str):
    """
    Get status of a specific job.
    """
    try:
        from supabase_storage import get_supabase_client
        supabase = get_supabase_client()

        reconcile_stale_jobs(supabase)
        
        result = supabase.table("job_queue").select("*").eq("id", job_id).single().execute()
        
        if not result.data:
            raise HTTPException(status_code=404, detail="Job not found")
        
        return result.data
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to get job: {str(e)}")


@router.get("/{job_id}/posts")
async def get_job_posts(job_id: str):
    """
    Get all blog posts generated by a specific job.
    """
    try:
        from supabase_storage import get_supabase_client
        supabase = get_supabase_client()
        
        result = supabase.table("blog_posts").select("*").eq("job_id", job_id).execute()
        
        return {
            "job_id": job_id,
            "posts": result.data if result.data else [],
            "count": len(result.data) if result.data else 0
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to get job posts: {str(e)}")


@router.delete("/{job_id}")
async def cancel_job(job_id: str):
    """
    Mark a pending or running job as cancelled.

    The current generator checks this state before persistence and completion,
    but a blocking model call that is already in progress cannot be interrupted.
    """
    try:
        from supabase_storage import get_supabase_client
        supabase = get_supabase_client()
        
        # Check current status
        job = supabase.table("job_queue").select("status").eq("id", job_id).single().execute()
        
        if not job.data:
            raise HTTPException(status_code=404, detail="Job not found")
        
        current_status = job.data["status"]
        if current_status == "cancelled":
            return {"message": "Job was already marked cancelled", "job_id": job_id}
        if current_status not in ACTIVE_JOB_STATUSES:
            raise HTTPException(
                status_code=409,
                detail=f"Cannot cancel job with status: {current_status}",
            )

        cancelled = transition_job(
            supabase,
            job_id,
            ACTIVE_JOB_STATUSES,
            {
                "status": "cancelled",
                "completed_at": isoformat_utc(),
                "error": "Marked cancelled by user",
            },
        )
        if not cancelled:
            raise HTTPException(
                status_code=409,
                detail="The job changed state before it could be cancelled. Refresh and try again.",
            )

        return {
            "message": "Job marked cancelled; in-flight model calls may take time to stop",
            "job_id": job_id,
        }
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to cancel job: {str(e)}")


@router.get("/{job_id}/logs")
async def get_job_logs(job_id: str):
    """
    Get logs for a specific job.
    """
    try:
        from supabase_storage import get_supabase_client
        supabase = get_supabase_client()
        
        # Get job to check logs in result
        result = supabase.table("job_queue").select("*").eq("id", job_id).single().execute()
        
        if not result.data:
            raise HTTPException(status_code=404, detail="Job not found")
        
        job = result.data
        logs = []
        
        # Extract logs from result if available
        if job.get("result") and job["result"].get("logs"):
            logs = job["result"]["logs"]
        
        return {
            "job_id": job_id,
            "status": job["status"],
            "logs": logs,
            "error": job.get("error")
        }
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to get job logs: {str(e)}")


@router.post("/cleanup")
async def cleanup_old_jobs(
    days_old: int = Query(default=30, ge=1, le=365, description="Delete jobs older than N days")
):
    """
    Clean up old completed/failed jobs.
    """
    try:
        from supabase_storage import get_supabase_client
        from datetime import timedelta
        supabase = get_supabase_client()
        
        cutoff_date = (datetime.utcnow() - timedelta(days=days_old)).isoformat()
        
        # Delete old completed and failed jobs
        result = supabase.table("job_queue").delete().lt(
            "completed_at", cutoff_date
        ).in_("status", ["completed", "failed", "cancelled"]).execute()
        
        deleted_count = len(result.data) if result.data else 0
        
        return {
            "message": f"Cleaned up {deleted_count} old jobs",
            "deleted_count": deleted_count,
            "cutoff_date": cutoff_date
        }
        
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to cleanup jobs: {str(e)}")


